# GitHub Sponsors / funding configuration
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
#
# This project is provided free of charge as MIT-licensed open-source
# software. Funding is optional and only used to cover infrastructure
# costs (domain, hosting) for the public documentation.

github: [zhouyoukang]
